name: Compile uBlock Origin Filters
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Compile filters
        run: python compile_filters.py
      - name: Save filters as artifact
        uses: actions/upload-artifact@v2
        with:
          name: filters.txt
          path: filters.txt
